require 'matrix'
require 'csv'
require 'thor'
require 'pry'

require_relative './custom_matrix'
require_relative './matrix/matrix'
require_relative './gaussian_solver/gaussian_solver'
require_relative './inverse_matrix_finder/inverse_matrix_finder'
require_relative './approximator/approximator'
require_relative './approximator/least_squares_approximator'
require_relative './integrator/integrator'
require_relative './integrator/trapezoid_integrator'
require_relative './differentiator/differentiator'
